export const PLANS = [
  {
    id: 'free',
    name: 'Explorador',
    price: 'Gratis',
    priceUsd: 0,
    desc: '7 días de prueba',
    trial: true,
    trialDays: 7,
    searchLimit: 3,
    resultsLimit: 10,
    countries: ['CL'],
    features: [
      '3 búsquedas durante el periodo de prueba',
      'Máx. 10 productos por búsqueda',
      'Solo Chile 🇨🇱',
      'Sin exportar datos',
    ],
    cta: 'Empezar prueba gratis',
    highlight: false,
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 'USD $29',
    priceUsd: 29,
    desc: '/mes · ~$27.500 CLP',
    trial: false,
    searchLimit: 50,
    resultsLimit: 50,
    countries: ['CL', 'MX', 'BR'],
    features: [
      '50 búsquedas por mes',
      'Máx. 50 productos por búsqueda',
      'Chile 🇨🇱 · México 🇲🇽 · Brasil 🇧🇷',
      'Exportar a CSV',
      'Datos actualizados diariamente',
    ],
    cta: 'Empezar ahora',
    highlight: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 'USD $59',
    priceUsd: 59,
    desc: '/mes · ~$56.000 CLP',
    trial: false,
    searchLimit: -1,
    resultsLimit: 100,
    countries: ['ALL'],
    features: [
      'Búsquedas ilimitadas',
      'Máx. 100 productos por búsqueda',
      '18 países LATAM completos',
      'Exportar CSV + Excel',
      'Historial de búsquedas',
      'Datos actualizados 2x al día',
      'Próximamente: métricas TikTok 🔜',
    ],
    cta: 'Activar Pro',
    highlight: true,
  },
  {
    id: 'agency',
    name: 'Agency',
    price: 'USD $150',
    priceUsd: 150,
    desc: '/mes · ~$142.000 CLP',
    trial: false,
    searchLimit: -1,
    resultsLimit: 500,
    countries: ['ALL'],
    features: [
      'Todo lo del plan Pro',
      'Hasta 5 usuarios simultáneos',
      'Acceso a API propia',
      'TikTok analytics completo 🔜',
      'Soporte prioritario por WhatsApp',
      'Reportes automáticos PDF semanales',
    ],
    cta: 'Contactar ventas',
    highlight: false,
  },
]
